.TH "lxpolkit" 1
.SH NAME
lxpolkit \- PolicyKit agent for LXDE
.SH SYNOPSIS
.B lxpolkit
.SH DESCRIPTION
.B lxpolkit
is a PolicyKit agent that communicates with the PolicyKit daemon to grant
applications extended privileges.
.SH AUTHORS
This manual page is written by Andriy Grytsenko <andrej@rep.kiev.ua>.
