.\" Process this file with
.\" groff -man -Tascii lxhotkey.1
.\"
.TH "lxpolkit" 1
.SH NAME
lxpolkit \- PolicyKit agent for LXDE

.SH SYNOPSIS
.B lxpolkit

.SH DESCRIPTION
.B lxpolkit
is a PolicyKit agent which interacts with PolicyKit daemon to provide
extended privileges to applications.

.SH OPTIONS
.B lxpolkit
does not support any options.

.SH AUTHORS
This manual page is written by Andriy Grytsenko <andrej@rep.kiev.ua>.
