.TH "lxsession-xdg-autostart" 1
.SH NAME
lxsession-xdg-autostart \- LXSession autostart runner
.SH SYNOPSIS
.BR lxsession-xdg-autostart
[\fIOPTION\fR]
.SH DESCRIPTION
\ \&
.br
OPTION
.RS
\fB\-d\fR, \fB\-\-desktop_environnement\fR=\fIname\fR
.ti +7
name of the desktop environnement (\fILXDE\fR is the default)
.RE
.TP
This program is for internal usage by lxsession. Never run it manually.
