'\" t
.\"     Title: LXSESSION
.\"    Author: Ying-Chun Liu
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: March  2, 2008
.\"    Manual: http://LXDE.org
.\"    Source: http://LXDE.org
.\"  Language: English
.\"
.TH "LXSESSION" "1" "March 2, 2008" "http://LXDE\&.org" "http://LXDE.org"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
lxsession-logout \- program to logout from LXSession
.SH "SYNOPSIS"
.HP \w'\fBlxsession\-logout\fR\ 'u
\fBlxsession\-logout\fR [\fBoptions\fR...]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBlxsession\-logout\fR
command\&.
.PP
\fBlxsession\-logout\fR
is a program that to logout from LXSession\&. It gives a good\-looking logout dialog\&.
.SH "OPTIONS"
.PP
These programs follow the usual
GNU
command line syntax, with long options starting with two dashes (`\-\*(Aq)\&. A summary of options is included below\&.
.PP
\fB\-\-prompt \fR\fB\fIYour custom message\fR\fR
.RS 4
Customize the logout message\&.
.RE
.PP
\fB\-\-banner \fR\fB\fIYour logo\fR\fR
.RS 4
Customize the logout logo\&.
.RE
.PP
\fB\-\-side left|top|right|bottom\fR
.RS 4
The position of the logo\&.
.RE
.SH "SEE ALSO"
.PP
lxsession (1)\&.
.SH "AUTHOR"
.PP
This manual page was written by paulliu
<grandpaul@gmail\&.com>
for the
Debian
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.SH "AUTHOR"
.PP
\fBYing\-Chun Liu\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2008 paulliu
.br
