.TH "lxsession-default" 1
.SH NAME
lxsession-default \- Launching default applications set by LXSession 
.SH SYNOPSIS
.B lxsession-default
[COMMAND]
[OPTIONS]

.SH DESCRIPTION

.B lxsession-default
is a wrapper around LXSession D-Bus interface, which launch default
applications set by LXsession.

COMMAND is the application you want to launch, and the ones available are
define in desktop.conf.examples.

OPTIONS are available if the COMMAND accept it.

Example :
To launch file_manager/command set in desktop.conf, use :
lxsession-default file_manager

.SH AUTHORS
Julien Lavergne <gilir@ubuntu.com>

Man page written to conform with Debian by Julien Lavergne.
