.TH "lxsession-default-terminal" 1
.SH NAME
lxsession-default-terminal \- Launching default terminal set by LXSession 
.SH SYNOPSIS
.B lxsession-default-terminal

.SH DESCRIPTION

.B lxsession-default-terminal
is a wrapper around LXSession D-Bus interface, which launch default
terminal set by LXsession. It's equivalent to lxsession-default terminal, but
it can be used if an application can't use lxsesison-default.

Applications launched will be the one define for terminal_manager/command set
in desktop.conf.

.SH AUTHORS
Julien Lavergne <gilir@ubuntu.com>

Man page written to conform with Debian by Julien Lavergne.
