.TH "lxsettings-daemon" "1"
.SH "NAME"
lxsettings-daemon \(em lightweight XSettings daemon for LXDE
.SH "SYNOPSIS"
.PP
.B lxsettings-daemon
\-f
.I file
.PP
This manual page documents briefly the
\fBlxsettings-daemon\fR command.
.SH "DESCRIPTION"
.PP
\fBlxsettings-daemon\fR is a program that provides
XSettings daemon. The daemon handles the session settings for applications.

\fBlxsettings-daemon\fR is a part of the LXDE project.
.SH "OPTIONS"
.PP
.TP 25
.BI \-f " file" "\fR,\fP \-\^\-file=" file
path to the configuration \fIfile\fP
.SH "AUTHOR"
.PP
This manual page was written by paulliu <grandpaul@gmail.com> for
the \fBDebian\fP system (but may be used by others).  Permission is
granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any
later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common-licenses/GPL.
