.TH "lxsession-default-app" 1
.SH NAME
lxsession-default-app \- Configure default applications for LXSession
.SH SYNOPSIS
.B lxsession-default-app

.SH DESCRIPTION

.B lxsession-default-app
is an utility to set up default applications and other options for LXSession.

.SH AUTHORS
Julien Lavergne (gilir@ubuntu.com)

Man page written to conform with Debian by Julien Lavergne.
