.TH "lxsession-default-apps" 1
.SH NAME
lxsession-default-apps \- configure default applications for LXSession
.SH SYNOPSIS
.B lxsession-default-apps
.SH DESCRIPTION
.B lxsession-default-apps
is a utility to set up default applications and settings for LXSession.
.SH AUTHORS
Julien Lavergne (gilir@ubuntu.com),
.br
man page written to conform with Debian
