.TH "lxsession-default-apps" 1
.SH NAME
lxsession-default-apps \- Configure default applications for LXSession
.SH SYNOPSIS
.B lxsession-default-apps

.SH DESCRIPTION

.B lxsession-default-apps
is an utility to set up default applications and other options for LXSession.

.SH AUTHORS
Julien Lavergne (gilir@ubuntu.com)

Man page written to conform with Debian by Julien Lavergne.
