.TH "lxsettings-daemon" "1"
.SH "NAME"
lxsettings-daemon \- lightweight XSettings daemon for LXDE
.SH "SYNOPSIS"
.PP
.B lxsettings-daemon \-f
.I file
.SH "DESCRIPTION"
.PP
\fBlxsettings-daemon\fR implements the XSETTINGS specification and provides
settings for X applications.
.SH "OPTIONS"
.PP
.TP
\fB\-f\fR, \fB\-\-file\fR \fIfile\fP
path to the configuration \fIfile\fP
.SH "AUTHORS"
.PP
This manual page was written by paulliu <grandpaul@gmail.com>.
.SH "COPYRIGHT"
.PP
Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any later version
published by the Free Software Foundation.
