#!/bin/sh
#
#  Copyright (C) 2013 Julien Lavergne (gilir@ubuntu.com)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

echo $1  # first argument
echo $2  # second argument

if [ "$1" = "audio" ]
then
	echo "Launching audio preferences"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/SessionManager org.lxde.SessionManager.AudioManagerLaunch > /dev/null 2>&1

elif [ "$1" = "quit" ]
then
	echo "Launching quit manager"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/SessionManager org.lxde.SessionManager.QuitManagerLaunch > /dev/null 2>&1

elif [ "$1" = "workspace" ]
then
	echo "Launching workspace manager"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/SessionManager org.lxde.SessionManager.WorkspaceManagerLaunch > /dev/null 2>&1

elif [ "$1" = "launcher" ]
then
	echo "Launching launcher manager"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/SessionManager org.lxde.SessionManager.LauncherManagerLaunch > /dev/null 2>&1

elif [ "$1" = "terminal" ]
then
	echo "Launching terminal manager"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/SessionManager org.lxde.SessionManager.TerminalManagerLaunch > /dev/null 2>&1

elif [ "$1" = "upgrades" ]
then
	echo "Launching upgrades manager"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/SessionManager org.lxde.SessionManager.UpgradesManagerLaunch > /dev/null 2>&1

elif [ "$1" = "screenshot" && "$2" = "window"]
then
	echo "Launching screenshot manager (current window)"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/ScreenshotManager org.lxde.SessionManager.ScreenshotWindowManagerLaunch
elif [ "$1" = "screenshot"]
then
	echo "Launching screenshot manager"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/ScreenshotManager org.lxde.SessionManager.ScreenshotManagerLaunch > /dev/null 2>&1

elif [ "$1" = "filemanager" ]
then
	echo "Launching file manager"
	dbus-send --session --print-reply --dest="org.lxde.SessionManager" /org/lxde/SessionManager org.lxde.SessionManager.FileManagerLaunch > /dev/null 2>&1

fi

exit 0
