#!/bin/sh -e

if [ "$1" = configure ]; then
  update-alternatives --install /usr/bin/x-session-manager \
    x-session-manager /usr/bin/lxsession 49 \
    --slave /usr/share/man/man1/lxsession-manager.1.gz \
    x-session-manager.1.gz /usr/share/man/man1/lxsession.1.gz 

fi

if [ -f /usr/share/update-notifier/notify-reboot-required ]; then
	exec /usr/share/update-notifier/notify-reboot-required
fi

#DEBHELPER#

exit 0
