#!/bin/sh
#
#
#  Copyright (C) 1999, 2003 Olivier Fourdan (fourdan@xfce.org)
#  Copyright (C) 2012 Julien Lavergne (gilir@ubuntu.com)
#  Copyright (C) 2013 Jarno Suni (8@iki.fi)
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

# Try to lock the screen with thos applications (in this order) :
# light-locker-command, xscreensaver, gnome-screensaver, slock, xlock, i3lock and xdg-screensaver

if pidof light-locker >/dev/null; then
    light-locker-command -l >/dev/null 2>&1
elif pidof xscreensaver >/dev/null; then
    xscreensaver-command -lock >/dev/null 2>&1
elif pidof gnome-screensaver >/dev/null; then
    gnome-screensaver-command --lock
elif which slock >/dev/null; then
    slock &
elif which xlock 2>/dev/null; then
    xlock $*
elif which i3lock >/dev/null; then
    i3lock -d
else
    # In the end, try to fallback to xscreensaver

    # assert: gnome-screensaver is not running
    xscreensaver -nosplash >/dev/null 2>&1 &
    xscreensaver-command -lock >/dev/null 2>&1
fi
exit 0
